### ISSUE TITLE
Syntax error on ml_convertRotationOrder

### ISSUE THREAD

**Issue by Lauloque** [morganloomis/ml_tools#2]
Hi!

Using Maya 2020, I can't use ml_convertRotationOrder, here's the script editor's output when I click the shelf button:

```python
import ml_convertRotationOrder
ml_convertRotationOrder.ui();
// Error: ml_convertRotationOrder.ui(); // 
// Error: Line 2.28: Syntax error // 
```

Also, not sure if I should bring this in another issue ticket or not but:  
I tried to install the module from here, but I don't understand the installation procedure.

I tried to just put the ml_tools-3.0.0 folder somewhere and write the suggested windows shell command (well I guess I did it correctly?)

I also tried to add the following line to *Documents\maya\2020\Maya.env* :  
`MAYA_ML_TOOLS = %MAYA_MODULE_PATH%/ml_tools-3.0.0`

But nothing else really happens, neither in an already running Maya or after rebooting Maya.

I tried to run a getenv in the script editor to see if Maya knows the path I set in Maya.env, which looks ok to me:
```python
getenv MAYA_ML_TOOLS;
// C:/Program Files/Common Files/Autodesk Shared/Modules/maya/ml_tools-3.0.0 // 
```

**Comment by Lauloque** [comment]
Turns out I'm just stupid and created a MEL button 🤦‍♂️

I figured out the rest with a Maya experienced friend of mine. Sorry for the inconvenience.

**Comment by morganloomis** [comment]
:)
